### ISSUE TITLE
HTTPS of https://sandbox.mydata.fi does not work and give errors on mydata-sdk

### ISSUE THREAD

**Issue by fititnt** [fititnt/mydata-sdk--hiit#2]
On #1, I cannot login, not sure if this error is or not related, but <https://sandbox.mydata.fi> (httpS) does not work, and <http://sandbox.mydata.fi> works.

```bash
operator_components       | INFO:debug:Making request GET https://sandbox.mydata.fi/registry/search/api/v1/services/582f2bf50cf2f4663ec4f020
operator_components       | ERROR:debug:HTTPSConnectionPool(host='sandbox.mydata.fi', port=443): Max retries exceeded with url: /registry/search/api/v1/services/582f2bf50cf2f4663ec4f020 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f0af8a306d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
operator_components       | Traceback (most recent call last):
operator_components       |   File "/mydata-sdk-components/Operator_Components/Templates.py", line 87, in getService
operator_components       |     req = get(self.registry_url+service_id)
operator_components       |   File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 70, in get
operator_components       |     return request('get', url, params=params, **kwargs)
operator_components       |   File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 56, in request
operator_components       |     return session.request(method=method, url=url, **kwargs)
operator_components       |   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
operator_components       |     resp = self.send(prep, **send_kwargs)
operator_components       |   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
operator_components       |     r = adapter.send(request, **kwargs)
operator_components       |   File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
operator_components       |     raise ConnectionError(e, request=request)
operator_components       | ConnectionError: HTTPSConnectionPool(host='sandbox.mydata.fi', port=443): Max retries exceeded with url: /registry/search/api/v1/services/582f2bf50cf2f4663ec4f020 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f0af8a306d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
operator_components       | {'status': 503, 'count': 0, 'trace': ['Traceback (most recent call last):', '  File "/mydata-sdk-components/Operator_Components/Operator_SLR/start.py", line 63, in get', '    service_json = self.service_registry_handler.getService(service_id)', '  File "/mydata-sdk-components/Operator_Components/Templates.py", line 93, in getService', '    raise e', "ConnectionError: HTTPSConnectionPool(host='sandbox.mydata.fi', port=443): Max retries exceeded with url: /registry/search/api/v1/services/582f2bf50cf2f4663ec4f020 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f0af8a306d0>: Failed to establish a new connection: [Errno 111] Connection refused',))"], 'title': 'Request to Service_Components Mgmnt failed due to ConnectionError.', 'detail': 'Service_Components Mgmnt might be down or unresponsive.', 'source': None, 'id': '13ae3866-d15d-4777-b606-a107ba5c4948'}
operator_components       | (['Traceback (most recent call last):', '  File "/mydata-sdk-components/Operator_Components/Operator_SLR/start.py", line 98, in get', '    trace=traceback.format_exc(limit=100).splitlines())', 'DetailedHTTPException: 503: Service Unavailable'], <type 'list'>)
operator_components       | ['Traceback (most recent call last):', '  File "/mydata-sdk-components/Operator_Components/Operator_SLR/start.py", line 98, in get', '    trace=traceback.format_exc(limit=100).splitlines())', 'DetailedHTTPException: 503: Service Unavailable']
operator_components       | {
operator_components       |   "errors": [
operator_components       |     {
operator_components       |       "status": 503, 
operator_components       |       "count": 0, 
operator_components       |       "trace": [
operator_components       |         "Traceback (most recent call last):", 
operator_components       |         "  File \"/mydata-sdk-components/Operator_Components/Operator_SLR/start.py\", line 63, in get", 
operator_components       |         "    service_json = self.service_registry_handler.getService(service_id)", 
operator_components       |         "  File \"/mydata-sdk-components/Operator_Components/Templates.py\", line 93, in getService", 
operator_components       |         "    raise e", 
operator_components       |         "ConnectionError: HTTPSConnectionPool(host='sandbox.mydata.fi', port=443): Max retries exceeded with url: /registry/search/api/v1/services/582f2bf50cf2f4663ec4f020 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f0af8a306d0>: Failed to establish a new connection: [Errno 111] Connection refused',))"
operator_components       |       ], 
operator_components       |       "title": "Request to Service_Components Mgmnt failed due to ConnectionError.", 
operator_components       |       "detail": "Service_Components Mgmnt might be down or unresponsive.", 
operator_components       |       "source": null, 
operator_components       |       "id": "13ae3866-d15d-4777-b606-a107ba5c4948"
operator_components       |     }, 
operator_components       |     {
operator_components       |       "status": 500, 
operator_components       |       "count": 1, 
operator_components       |       "trace": [
operator_components       |         "Traceback (most recent call last):", 
operator_components       |         "  File \"/mydata-sdk-components/Operator_Components/Operator_SLR/start.py\", line 98, in get", 
operator_components       |         "    trace=traceback.format_exc(limit=100).splitlines())", 
operator_components       |         "DetailedHTTPException: 503: Service Unavailable"
operator_components       |       ], 
operator_components       |       "title": "SLR registration failed.", 
operator_components       |       "detail": "Something failed during creation of SLR.", 
operator_components       |       "source": "Not resolved", 
operator_components       |       "id": "aaac0066-eeec-4995-adf7-c2ad726c3a28"
operator_components       |     }
operator_components       |   ]
operator_components       | }

```

**Comment by fititnt** [comment]
![captura de tela de 2018-04-20 20-26-23](https://user-images.githubusercontent.com/812299/39077608-af1e49c2-44d9-11e8-9b95-4b70fc15d31d.png)

**Comment by fititnt** [comment]
Humm, maybe not just about https, but the URL itself. This comment give me a hint https://github.com/HIIT/mydata-sdk/issues/7#issuecomment-311458261



![captura de tela de 2018-04-20 20-46-25](https://user-images.githubusercontent.com/812299/39077930-ecb35690-44db-11e8-8548-c8d1518b3832.png)
